import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/studentNavbar";
import { AuthProvider } from "@/context/AuthContext";
import AuthGate from "../components/AuthGate";

export const metadata = {
  title: "LevelUp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        <AuthGate>
          {children}
        </AuthGate>
      </AuthProvider>
      </body>
    </html>
  );
}
